### ISSUE TITLE
Transfer event should be fired in `issueSecurityTokens`

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core-deprecated#51]
Otherwise we are not conforming to the ERC20 spec. - transfers should be from the owner to the recipient I believe (not from 0x0). Arguably the initial allocation of totalSupply to the owner:  
`balances[_owner] = _totalSupply;`
should issue a Transfer event from 0x0 to _owner as well.

**Comment by satyamakgec** [comment]
#22

**Comment by pabloruiz55** [comment]
@satyamakgec it's not the same as #22 . Actually, the event that is actually present should be modified.
The issueSecurityToken func should trigger a Transfer event to keep it consistent. Otherwise, exchanges/wallets won't be able to find these transactions as they will be looking for Transfer event.

**Comment by adamdossa** [comment]
@pabloruiz55 @satyamakgec agree - this function needs to fire a Transfer event. It does not need to use the `transfer` or `transferFrom` function to do this, but can just do it internally itself.
