### ISSUE TITLE
setSTO can be called multiple times for the same offering and by anyone

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core-deprecated#59]
setSTO can be called by anyone any amount of times, effectively overriding whatever data was assigned to the offering mapping

**Comment by satyamakgec** [comment]
We can't restrict the caller I suppose because `Compliance.sol` is the generalised contract and this function is only used to avail the STO contract on the platform.  and STO contract will be exercised only through selecting the offering by Issuer then it doesn't affect who is adding the STO only matters whether they are selected by the issuers or not

**Comment by pabloruiz55** [comment]
This was ultimately fixed by adding:
```
require(offerings[_STOAddress].auditor == address(0));
```
