### ISSUE TITLE
Security token exists in registrar checks

### ISSUE THREAD

**Issue by sangheraio** [PolymathNetwork/polymath-core-deprecated#72]
Compliance.sol could check if the security token exists in the registrar before proposing a template or STO contract. This would prevent non-security token addresses from being added into the template history and potentially gaming the reputation.

**Comment by satyamakgec** [comment]
As @adamdossa  proposed to use withdraw function called from registrar only to prevent the same.

**Comment by pabloruiz55** [comment]
This is closely related to #64. Rather than checking that ST exists in Registrar before proposing a template/STO contract, I'd require that ST only be created by a Registrar contract.

This could be done either by requiring that msg.sender be the STR contract in the ST constructor. OR, by having the ST constructor be passed the STR address and call an STR function that adds the ST to STR's mapping.

**Comment by satyamakgec** [comment]
Crux of discussion with list of possible ways - 
1. @adamdossa suggested calling the withdraw functions from STR only so if the ST will be created by any other mean then the stakeholders (issuer, delegate, auditor) can't withdrawal their funds. This way we are not able to restrict the creation of ST by another mean. The user will know only when they are going to withdraw poly that they are playing with unauthenticated ST. (__This suggested solution is already implemented in the current version of the core__)

2.  @Everhusk way - "Compliance.sol could check if the security token exists in the registrar before proposing a template or STO contract. This would prevent non-security token addresses from being added into the template history and potentially be gaming the reputation". 
This way we will also not able to restrict the creation of the ST from STR but in that case, the user doesn't get fooled because ST will not be active because we restricting the false ST to proposing the template and STO.

3. @pabloruiz55 way - 

-  "This could be done either by requiring that msg.sender be the STR contract in the ST constructor".  I think in that case we need to hardcode the STR address in ST contract. through it, we can restrict the creation of the false ST but I don't think that will the feasible way to hardcode the contract address.

- "By having the ST constructor be passed the STR address and call an STR function that adds the ST to STR's mapping".  In this case, an issuer can fool us by sending the other contract address that has the similar mapping and functions that will be deployed by himself and through this issuer can pass the security check and launch the ST.

My suggestion is to implement @Everhusk way + @adamdossa  way or @Everhusk  way only. 
@Everhusk @pabloruiz55 @adamdossa provide your suggestion which possible way you suggest to go.

**Comment by pabloruiz55** [comment]
Ok. As it is now I don't like it as it offers a poor user experience. @Everhusk solution is a bit better as they learn earlier that what they are doing won't work.
Still, I'd rather directly prevent the creation of an ST if it is not done through the Registrar, or registered at ST construction time. 
If we won't do that, then go ahead and do it with @Everhusk suggestion. The earlier we can fail due to the ST not being created through the STR, the better.
